** Numpy Stands for Numerical Python we need to include Numpy package

In [73]:
import numpy as np

list to Numpy array

In [74]:
lst=[10,20,30,40]
np_lst=np.array(lst)
np_lst

array([10, 20, 30, 40])

**Creating 1,2,3  Dimension  array**

In [75]:
D1=np.array([5,7,9])
D2=np.array([[0,1,2],[5,7,9]])
D3=np.array([[[0,1,2],[5,7,9],[4,6,9]],[[0,1,2],[5,7,9],[4,6,9]]])

**Getting the Shape of Array**

In [76]:
print('D1 Shape:',D1.shape)
print('D2 Shape:',D2.shape)
print('D3 Shape:',D3.shape)

D1 Shape: (3,)
D2 Shape: (2, 3)
D3 Shape: (2, 3, 3)


**Getting the Dimemsion of array:**

In [77]:
print('D1 Dimension:',D1.ndim)
print('D2 Dimension:',D2.ndim)
print('D3 Dimension:',D3.ndim)

D1 Dimension: 1
D2 Dimension: 2
D3 Dimension: 3


**Getting the Size of numpy array**

In [78]:
print('D1 Size:',D1.size)
print('D2 Size:',D2.size)
print('D3 Size:',D3.size)

D1 Size: 3
D2 Size: 6
D3 Size: 18


In [79]:
string_arr=np.array(['England','India','Srilanka','China'])
string_arr

array(['England', 'India', 'Srilanka', 'China'], dtype='<U8')

**Getting the datatype:**

In [80]:
print('D1 Datatype:',D1.dtype)
print('D2 Datatype:',D2.dtype)
print('D1 Datatype:',D1.dtype)
print('string_arr Datatype:',string_arr.dtype)

D1 Datatype: int64
D2 Datatype: int64
D1 Datatype: int64
string_arr Datatype: <U8


**Simple Operation like add or delete(both Array Should be in same size)**

In [81]:
first_ele=np.array([10,20,30,40])
secon_ele=np.array([40,30,20,10])
Final_ele_add=first_ele+secon_ele
Final_ele_sub=first_ele-secon_ele
print('Addition: ',Final_ele_add)
print('Substract: ',Final_ele_sub)

Addition:  [50 50 50 50]
Substract:  [-30 -10  10  30]


**Array Slicing**

In [82]:
print('Full Array',D3)
print('First row',D3[0])
print('second row of first row',D3[0][1])
print('second row of first row and second element',D3[0][1][1])

Full Array [[[0 1 2]
  [5 7 9]
  [4 6 9]]

 [[0 1 2]
  [5 7 9]
  [4 6 9]]]
First row [[0 1 2]
 [5 7 9]
 [4 6 9]]
second row of first row [5 7 9]
second row of first row and second element 7


**boolean Operation**

In [83]:
D2=np.array([[50,60,80],[40,45,80]])
D2_boolean=D2 > 50
print(D2_boolean)
#Filtering the element on array
print(D2[D2_boolean])

[[False  True  True]
 [False False  True]]
[60 80 80]


**Shallow Copy and deep copy**

In [84]:
string_arr_direct=string_arr
string_arr_direct_vw=string_arr.view()
string_arr_direct_cp=string_arr.copy()
print("Direct Copy",string_arr_direct)
print("shallow  Copy",string_arr_direct_vw)
print("Deep  Copy",string_arr_direct_cp)
string_arr[0]='Scotland'
print("Direct Copy after assingment",string_arr_direct)
print("shallow Copy after assingment",string_arr_direct_vw)
print("Deep  Copy after assingment",string_arr_direct_cp)

Direct Copy ['England' 'India' 'Srilanka' 'China']
shallow  Copy ['England' 'India' 'Srilanka' 'China']
Deep  Copy ['England' 'India' 'Srilanka' 'China']
Direct Copy after assingment ['Scotland' 'India' 'Srilanka' 'China']
shallow Copy after assingment ['Scotland' 'India' 'Srilanka' 'China']
Deep  Copy after assingment ['England' 'India' 'Srilanka' 'China']


**sqrt,cos,pi,exp,sin,floor**

**shape manipulation(ravel,reshape,resize,split and stack)**

In [85]:
arr=np.array([[0,2,'txt'],[2.0,3,True]])

In [86]:
flatted=arr.ravel()
print(flatted)

['0' '2' 'txt' '2.0' '3' 'True']


In [87]:
flatted.reshape(3,2)

array([['0', '2'],
       ['txt', '2.0'],
       ['3', 'True']], dtype='<U21')

In [88]:
flatted.resize(3,2)
flatted

array([['0', '2'],
       ['txt', '2.0'],
       ['3', 'True']], dtype='<U21')

In [89]:
np.hsplit(flatted,2)

[array([['0'],
        ['txt'],
        ['3']], dtype='<U21'), array([['2'],
        ['2.0'],
        ['True']], dtype='<U21')]

In [90]:
flatted

array([['0', '2'],
       ['txt', '2.0'],
       ['3', 'True']], dtype='<U21')

In [93]:
np.stack((np.array([0,1,2,3,4]),np.array([5,6,7,8,9])))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
np.hstack((np.array([0,1,2,3,4]),np.array([5,6,7,8,9])))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Numpy Array broadcasting(Array should be with similar size or scalar**

In [107]:
arr=np.array([[1,2],[3,4]])
print(arr)
n=.2
arr_new=arr*n
print(arr_new)

[[1 2]
 [3 4]]
[[0.2 0.4]
 [0.6 0.8]]


**Trace**

In [109]:
print(np.trace(arr_new))

1.0


**Transpose**

In [113]:
print(D3)
D3.transpose()

[[[0 1 2]
  [5 7 9]
  [4 6 9]]

 [[0 1 2]
  [5 7 9]
  [4 6 9]]]


array([[[0, 0],
        [5, 5],
        [4, 4]],

       [[1, 1],
        [7, 7],
        [6, 6]],

       [[2, 2],
        [9, 9],
        [9, 9]]])

x-y+3z=2
2x+y+2z=2
-2x-2y+z=3
find x,y,z?

In [116]:
A=np.array([[1,-1,3],[2,1,2],[-2,-2,1]])

In [117]:
A

array([[ 1, -1,  3],
       [ 2,  1,  2],
       [-2, -2,  1]])

In [118]:
ainv=np.linalg.inv(A)
print(ainv)

[[ 1.  -1.  -1. ]
 [-1.2  1.4  0.8]
 [-0.4  0.8  0.6]]


In [127]:
res=[2,2,3]#as shpwing result into 1D array

In [120]:
result=np.dot(ainv,A)
print(result)

In [125]:
result=np.dot(ainv,res)

In [126]:
result

array([-3. ,  2.8,  2.6])

# x=-3,y=2.8,z=2.6