In [2]:
from scipy.integrate import quad

In [10]:
def integration(x):
    return x

In [8]:
quad(integration,0,10)

(60.0, 6.661338147750939e-13)

In [12]:
for i in range(10):
    result=quad(integration,0,i)
    print(i,'',result[0])

0  0.0
1  0.5
2  2.0
3  4.5
4  8.0
5  12.5
6  18.0
7  24.5
8  32.0
9  40.5


In [13]:
import numpy as np

In [14]:
np.pi

3.141592653589793

In [19]:
def integrate_f1(x1,a,b):
    return x1**a+b

In [16]:
a=3
b=5

In [20]:
quad(integrate_f1,1,2, args=(a,b))

(8.75, 9.71445146547012e-14)

In [21]:
from scipy.integrate import dblquad

In [22]:
def dbl_integrate(x,y):
    return x**y

In [24]:
dblquad(dbl_integrate,1,10,0,2)

(318.146830579631, 1.8679405911760298e-08)

In [35]:
from scipy import optimize
def min_check(x):
    return x**2
minima=optimize.minimize(min_check,x0=0,method='bfgs')
minima

      fun: array([0.])
 hess_inv: array([[1]])
      jac: array([1.49011612e-08])
  message: 'Optimization terminated successfully.'
     nfev: 3
      nit: 0
     njev: 1
   status: 0
  success: True
        x: array([0.])

In [37]:
from scipy.optimize import root
def root_check(x):
    return x-5
rootVal=root(root_check,1)
rootVal

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 4
     qtf: array([-8.72457662e-12])
       r: array([-1.])
  status: 1
 success: True
       x: array([5.])

In [38]:
from scipy import linalg

In [40]:
matrix=np.array([[10,6],[10,7]])

In [41]:
linalg.inv(matrix)

array([[ 0.7, -0.6],
       [-1. ,  1. ]])

In [42]:
linalg.det(matrix)

9.999999999999991

In [44]:
numarr=np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [45]:
numval=np.array([21,9,6])

In [46]:
linalg.solve(numarr,numval)

array([ 4.95,  4.35, -1.95])

In [47]:
linalg.svd(numarr)

(array([[-0.2344097 , -0.33590599, -0.91226052],
        [-0.48608065, -0.77217819,  0.40922663],
        [-0.84188936,  0.53935888,  0.01772866]]),
 array([11.16574895,  4.40001239,  2.44252764]),
 array([[-0.22465191, -0.43144541, -0.87371985],
        [ 0.39055409, -0.86133648,  0.32491072],
        [-0.89274802, -0.26824305,  0.36200365]]))

In [48]:
linalg.eig(numarr)

(array([ 2.43605364+2.20212523j,  2.43605364-2.20212523j,
        11.12789272+0.j        ]),
 array([[-0.68042093+0.j        , -0.68042093-0.j        ,
          0.25476719+0.j        ],
        [-0.19146796-0.5904854j , -0.19146796+0.5904854j ,
          0.49907529+0.j        ],
        [ 0.27770387+0.27308412j,  0.27770387-0.27308412j,
          0.82826175+0.j        ]]))

In [50]:
linalg.eigvals(numarr)

array([ 2.43605364+2.20212523j,  2.43605364-2.20212523j,
       11.12789272+0.j        ])

Use SciPy to solve a linear algebra problem.

There is a test with 30 questions worth 150 marks. The test has two types of questions:

1. True or false – carries 4 marks each

2. Multiple-choice – carries 9 marks each

Find the number of true or false and multiple-choice questions.

In [4]:
import numpy as np
from scipy import linalg
matrix=np.array([[1,1],[4,9]])
result=np.array([30,150])

In [5]:
linalg.solve(matrix,result)

array([24.,  6.])

Use SciPy to declare 20 random values for random values and perform the following:

1. CDF – Cumulative Distribution Function for 10 random variables.

2. PDF – Probability Density Function for 14 random variables.

In [7]:
from scipy.stats import norm

In [12]:
norm.rvs(loc=0,scale=1,size=20)

array([ 1.3468805 , -0.0665651 , -1.19856137,  0.05137075,  0.35802855,
        0.08667632, -0.2510398 , -0.01872043, -0.45717145, -0.86187342,
        0.6362505 , -0.83826283, -0.19615273,  1.33231786,  0.2241585 ,
        0.87641834, -0.73111364, -1.6620922 , -0.59751255, -2.02356689])

In [13]:
norm.cdf(10,loc=1,scale=3)

0.9986501019683699

In [15]:
norm.pdf(14,loc=1,scale=1)

7.998827757006813e-38