**Run the Cell to import the packages**

In [2]:
import pandas as pd
import numpy as np

**Data Loading**
**Fill in the Command to load your CSV dataset "weather.csv" with pandas**

In [3]:
weather = pd.read_csv('weather.csv', sep=',',index_col='index')
weather

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
index                                                                           
0      2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1      2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2      2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3      2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4      2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
...           ...      ...      ...      ...       ...          ...       ...   
24995  2013-03-09  Penrith     16.5     30.0       0.0          NaN       NaN   
24996  2013-03-10  Penrith     16.7     30.5       0.0          NaN       NaN   
24997  2013-03-11  Penrith     18.3     29.8       0.0          NaN       NaN   
24998  2013-03-12  Penrith     17.5     28.1       0.0          NaN       NaN   
24999  2013-03-13  Penrith     15.4     30.9       0.0          NaN       NaN   

      WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
index                                        ...                            
0               W           44.0          W  ...        22.0       1007.7   
1             WNW           44.0        NNW  ...        25.0       1010.6   
2             WSW           46.0          W  ...        30.0       1007.6   
3              NE           24.0         SE  ...        16.0       1017.6   
4               W           41.0        ENE  ...        33.0       1010.8   
...           ...            ...        ...  ...         ...          ...   
24995          NE           26.0        SSE  ...        41.0          NaN   
24996          NE           24.0        ESE  ...        44.0          NaN   
24997         ENE           26.0        NaN  ...        49.0          NaN   
24998         NNE           22.0          S  ...        54.0          NaN   
24999          NE           24.0         NE  ...        39.0          NaN   

       Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
index                                                                          
0           1007.1       8.0       NaN     16.9     21.8         No      0.0   
1           1007.8       NaN       NaN     17.2     24.3         No      0.0   
2           1008.7       NaN       2.0     21.0     23.2         No      0.0   
3           1012.8       NaN       NaN     18.1     26.5         No      1.0   
4           1006.0       7.0       8.0     17.8     29.7         No      0.2   
...            ...       ...       ...      ...      ...        ...      ...   
24995          NaN       NaN       NaN     21.6     29.4         No      0.0   
24996          NaN       NaN       NaN     21.3     29.0         No      0.0   
24997          NaN       NaN       NaN     20.6     28.2         No      0.0   
24998          NaN       NaN       NaN     21.2     26.8         No      0.0   
24999          NaN       NaN       NaN     20.0     30.3         No      0.0   

       RainTomorrow  
index                
0                No  
1                No  
2                No  
3                No  
4                No  
...             ...  
24995            No  
24996            No  
24997            No  
24998            No  
24999            No  

[25000 rows x 24 columns]

**Data Analysis**

- Get the shape of the dataset and print it.

- Get the column names in list and print it.

- Describe the dataset to understand the basic statistics of the dataset.

- Print the first three rows of the dataset

In [5]:
print(weather.shape)
print("-----------------------------------------------")

print(weather.columns)
print("-----------------------------------------------")
print(      weather.describe()                )
print("-----------------------------------------------")
print(     weather.head(3)                   )

(25000, 24)
-----------------------------------------------
Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')
-----------------------------------------------
            MinTemp       MaxTemp      Rainfall  Evaporation     Sunshine  \
count  24669.000000  24824.000000  24721.000000  9432.000000  6664.000000   
mean      13.294568     23.990558      2.674467     5.825138     7.811945   
std        5.848304      6.114348      9.720306     4.871567     3.718698   
min       -3.300000      6.800000      0.000000     0.000000     0.000000   
25%        8.900000     19.500000      0.000000     3.000000     5.500000   
50%       14.000000     23.400000      0.000000     4

**Target Identification**

Execute the below cell to identify the target variables. If yes it will Rain Tommorow otherwise it will not Rain.

In [6]:
weather_target=weather['RainTomorrow'] 

print(weather_target)

0        No
1        No
2        No
3        No
4        No
         ..
24995    No
24996    No
24997    No
24998    No
24999    No
Name: RainTomorrow, Length: 25000, dtype: object


**Feature Identification**

In our case by analyzing the dataset, we can understand that the columns like **Date** might be irrelevant as they are not dependent on call usage pattern.

Since **RainTomorrow** is our target variable, we will be removing it from the feature set.

- Perform appropriate operation to drop the columns **Date** and **RainTomorrow** 

In [7]:
cols_to_drop = ['Date','RainTomorrow']

weather_feature = weather.drop(columns=['Date', 'RainTomorrow'])

print(weather_feature.head(5))

   index Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0      0   Albury     13.4     22.9       0.6          NaN       NaN   
1      1   Albury      7.4     25.1       0.0          NaN       NaN   
2      2   Albury     12.9     25.7       0.0          NaN       NaN   
3      3   Albury      9.2     28.0       0.0          NaN       NaN   
4      4   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN 

**Categorical Data**

In order to Identify the categorical variable in a data, use the following command in the below cell,

In [8]:
weather_categorical = weather.select_dtypes(include=[object])
print(weather_categorical.head(15))

          Date Location WindGustDir WindDir9am WindDir3pm RainToday  \
0   2008-12-01   Albury           W          W        WNW        No   
1   2008-12-02   Albury         WNW        NNW        WSW        No   
2   2008-12-03   Albury         WSW          W        WSW        No   
3   2008-12-04   Albury          NE         SE          E        No   
4   2008-12-05   Albury           W        ENE         NW        No   
5   2008-12-06   Albury         WNW          W          W        No   
6   2008-12-07   Albury           W         SW          W        No   
7   2008-12-08   Albury           W        SSE          W        No   
8   2008-12-09   Albury         NNW         SE         NW        No   
9   2008-12-10   Albury           W          S        SSE       Yes   
10  2008-12-11   Albury           N        SSE        ESE        No   
11  2008-12-12   Albury         NNE         NE        ENE       Yes   
12  2008-12-13   Albury           W        NNW        NNW       Yes   
13  20

**Convert to boolean**

Assign the column **RainToday** for the variable **yes_no_cols** and run the below cell to print first 5 rows of **weather_feature**


In [9]:
yes_no_cols = ["RainToday"]

weather_feature[yes_no_cols] = weather_feature[yes_no_cols] == 'Yes'

print(weather_feature.head(5))

   index Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0      0   Albury     13.4     22.9       0.6          NaN       NaN   
1      1   Albury      7.4     25.1       0.0          NaN       NaN   
2      2   Albury     12.9     25.7       0.0          NaN       NaN   
3      3   Albury      9.2     28.0       0.0          NaN       NaN   
4      4   Albury     17.5     32.3       1.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   
2         WSW           46.0          W  ...        38.0         30.0   
3          NE           24.0         SE  ...        45.0         16.0   
4           W           41.0        ENE  ...        82.0         33.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN 

**One Hot Encoding**

Execute the below cells to perform **One Hot Encoding**

In [10]:
weather_dumm=pd.get_dummies(weather_feature, columns=["Location","WindGustDir","WindDir9am","WindDir3pm"], prefix=["Location","WindGustDir","WindDir9am","WindDir3pm"])

weather_matrix = weather_dumm.values.astype(np.float)
weather_matrix

array([[0.0000e+00, 1.3400e+01, 2.2900e+01, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [1.0000e+00, 7.4000e+00, 2.5100e+01, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       [2.0000e+00, 1.2900e+01, 2.5700e+01, ..., 0.0000e+00, 0.0000e+00,
        1.0000e+00],
       ...,
       [2.4997e+04, 1.8300e+01, 2.9800e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.4998e+04, 1.7500e+01, 2.8100e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.4999e+04, 1.5400e+01, 3.0900e+01, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

**Imputing-Missing Values**

Do the Imputing-Missing Values by using the following parameters

 - missing_values=np.nan
 - strategy=mean
 - fill_value=None
 - verbose=0
 - copy=True
 

In [25]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy='mean',fill_value=None,verbose=0,copy=True )
weather_matrix=imp.fit_transform(weather_matrix)
weather_matrix

array([[-1.73198153,  0.01814869, -0.17899517, ..., -0.23760696,
         4.54780906, -0.23277696],
       [-1.73184296, -1.0146706 ,  0.18209479, ..., -0.23760696,
        -0.2198861 ,  4.29595774],
       [-1.7317044 , -0.06791959,  0.28057387, ..., -0.23760696,
        -0.2198861 ,  4.29595774],
       ...,
       [ 1.7317044 ,  0.86161777,  0.95351424, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [ 1.73184296,  0.72390853,  0.67449019, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [ 1.73198153,  0.36242178,  1.13405922, ..., -0.23760696,
        -0.2198861 , -0.23277696]])

**Standardization**

Run the below cell to perform standardization

In [19]:
from sklearn.preprocessing import StandardScaler

#Standardize the data by removing the mean and scaling to unit variance

scaler = StandardScaler()

#Fit to data, then transform it.

weather_matrix = scaler.fit_transform(weather_matrix)
weather_matrix

array([[-1.73198153,  0.01814869, -0.17899517, ..., -0.23760696,
         4.54780906, -0.23277696],
       [-1.73184296, -1.0146706 ,  0.18209479, ..., -0.23760696,
        -0.2198861 ,  4.29595774],
       [-1.7317044 , -0.06791959,  0.28057387, ..., -0.23760696,
        -0.2198861 ,  4.29595774],
       ...,
       [ 1.7317044 ,  0.86161777,  0.95351424, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [ 1.73184296,  0.72390853,  0.67449019, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [ 1.73198153,  0.36242178,  1.13405922, ..., -0.23760696,
        -0.2198861 , -0.23277696]])

**Train and Test Data**

Splitting the data for training and testing(90% train,10% test)

- Perform train-test split on **weather_matrix** and **weather_target** with 90% as train data and 10% as test      data.

In [20]:
from sklearn.model_selection import train_test_split

seed=5000

train_data,test_data, train_label, test_label = train_test_split( weather_matrix, weather_target, test_size=0.1, random_state=seed)
train_data

array([[ 0.95851692,  1.06818163,  0.03437617, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [-1.53549768,  0.4312764 ,  2.11885002, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [ 0.10842638,  1.29195914,  1.46232282, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       ...,
       [ 1.47397524,  1.25753183,  0.26416069, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [-1.5277381 ,  0.86161777, -0.29388743, ...,  4.20863099,
        -0.2198861 , -0.23277696],
       [ 1.73031876,  0.48291737, -0.9668278 , ..., -0.23760696,
        -0.2198861 , -0.23277696]])

**Random Forest Classifier**

- Do the **Random Forest** Classifier of the Dataset using the following parameters.
   - max_depth=5
   - n_estimators=10
   - max_features=10 
   - random_state=seed 
   
- Train the model with train_data and train_label.

- Now predict the output with test_data.

- Evaluate the classifier with score from test_data and test_label.


In [17]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier( max_depth=5, n_estimators=10,  max_features=10, random_state=seed)

classifier = classifier.fit(     train_data,  train_label  )

churn_predicted_target=classifier.predict( test_data )

score = classifier.score( test_data,test_label)

print('Random Forest Classifier : ',   score   )

with open('output1.txt', 'w') as file:
    file.write(str(np.mean(score)))

Random Forest Classifier :  0.9484
