<a href="https://colab.research.google.com/github/Santanukolkata/Data_Science/blob/master/Models/Linear_Regression/Lin_reg_multi_co_linearity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reference :
https://stattrek.com/multiple-regression/regression-coefficients.aspx

In [1]:
import pandas as pd
price = [160,180,200,220,240,260,280]
sale = [126,103,82,75,82,40,20]
cars = [0,9,19,5,25,1,20]
priceDF = pd.DataFrame(price, columns=list('x'))
saleDF = pd.DataFrame(sale, columns=list('y'))
carsDf = pd.DataFrame(cars, columns=list('z'))
houseDf = pd.concat([priceDF,saleDF,carsDf],axis=1)
X = houseDf.drop(['y'], axis=1)
y = houseDf.y

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [4]:

# Instantiate
linreg = LinearRegression()

# Fit
linreg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
linreg.coef_

array([-0.82493525,  0.35927476])

In [50]:
linreg.intercept_

252.85965331739396

In [13]:
y_hat = np.array(X).dot(np.array(linreg.coef_)).flatten() + linreg.intercept_ 

In [9]:
Y_predict =linreg.predict(X)

In [10]:
Y_predict

array([120.87001395, 107.60478183,  94.69882447,  73.17027296,
        63.85706316,  38.7357641 ,  29.06327954])

In [14]:
y_hat

array([120.87001395, 107.60478183,  94.69882447,  73.17027296,
        63.85706316,  38.7357641 ,  29.06327954])

In [49]:
np.set_printoptions(suppress=True)
X1 = np.array([160,180,200,220,240,260,280])
X2 = np.array([0,9,19,5,25,1,20])
Y = np.array([126,103,82,75,82,40,20])

X=np.column_stack((X1,X2))
X=np.column_stack((np.ones(len(Y)),X))
print(X)
X1 =np.transpose(X).dot(X)
print(np.transpose(X))
X1=np.transpose(X).dot(X)
print(X1)
X2 =np.linalg.inv(X1)
print(X2)
X3 =X2.dot(np.transpose(X).dot(Y))
X3




[[  1. 160.   0.]
 [  1. 180.   9.]
 [  1. 200.  19.]
 [  1. 220.   5.]
 [  1. 240.  25.]
 [  1. 260.   1.]
 [  1. 280.  20.]]
[[  1.   1.   1.   1.   1.   1.   1.]
 [160. 180. 200. 220. 240. 260. 280.]
 [  0.   9.  19.   5.  25.   1.  20.]]
[[     7.   1540.     79.]
 [  1540. 350000.  18380.]
 [    79.  18380.   1493.]]
[[ 4.6  -0.02  0.02]
 [-0.02  0.   -0.  ]
 [ 0.02 -0.    0.  ]]


array([252.86,  -0.82,   0.36])

In [26]:
np.transpose(X)

array([[  1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [160., 180., 200., 220., 240., 260., 280.],
       [  0.,   9.,  19.,   5.,  25.,   1.,  20.]])

In [54]:
X1 = np.array([160,180,200,220,240,260,280]).reshape(-1,1)
Y = np.array([126,103,82,75,82,40,20])
# Instantiate
linreg = LinearRegression()

# Fit
linreg.fit(X1, Y)

print(linreg.coef_)
print(linreg.intercept_)



mean_x1 = np.mean(X1)
mean_x2 = np.mean(X2)
mean_y = np.mean(Y)

n = len(X1)

# Using the formula to calculate b1 and b2
numer = 0
denom = 0

for i in range(n):
    numer += (X1[i] - mean_x1) * (Y[i] - mean_y)
    denom += (X1[i] - mean_x1) ** 2
    
b1 = numer / denom
b0 = mean_y - (b1 * mean_x1)

# Printing coefficients
print(b1,b0)



[-0.79]
249.8571428571429
[-0.79] [249.86]
