Import two modules sklearn.datasets, and sklearn.model_selection.
Import numpy and set random seed to 100.

Load popular Boston dataset from sklearn.datasets module and assign it to variable boston.

Split boston.data into two sets names X_train and X_test. Also, split boston.target into two sets Y_train and Y_test.

Hint: Use train_test_split method from sklearn.model_selection; set random_state to 30.
Print the shape of X_train dataset.

Print the shape of X_test dataset.

In [62]:
from  sklearn.datasets import load_boston
from  sklearn.model_selection import train_test_split
import numpy
data=load_boston()
x=data.data
y=data.target
X_train,X_test, Y_train,Y_test=train_test_split(x,y,random_state=30)
print(X_train.shape)
print(X_test.shape)

(379, 13)
(127, 13)


Import required module from sklearn.tree.

Build a Decision tree Regressor model from X_train set and Y_train labels, with default parameters. Name the model as dt_reg.

Evaluate the model accuracy on training data set and print it's score.

Evaluate the model accuracy on testing data set and print it's score.

Predict the housing price for first two samples of X_test set and print them.(Hint : Use predict() function)

In [63]:
from sklearn.tree import DecisionTreeRegressor

In [64]:
dt_reg=DecisionTreeRegressor()

In [65]:
dt_reg.fit(X_train,Y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [66]:
dt_reg.score(X_train,Y_train)

1.0

In [67]:
dt_reg.score(X_test,Y_test)

0.7111679501155957

In [68]:
dt_reg.predict(X_test[[0]])

array([18.2])

In [69]:
X_train[0]

array([  3.32105,   0.     ,  19.58   ,   1.     ,   0.871  ,   5.403  ,
       100.     ,   1.3216 ,   5.     , 403.     ,  14.7    , 396.9    ,
        26.82   ])

In [70]:
type(X_train)

numpy.ndarray

In [71]:
dt_reg.predict(X_test[[1]])

array([12.8])

In [72]:
Y_test[0]

19.6

In [73]:
Y_test[1]

10.5

In [74]:
from sklearn.tree import DecisionTreeRegressor
dt_reg=DecisionTreeRegressor()
dt_reg.fit(X_train,Y_train)
print(dt_reg.score(X_train,Y_train))
print(dt_reg.score(X_test,Y_test))
fm=dt_reg.predict(X_test[[0]])
fm1=dt_reg.predict(X_test[[1]])
print(fm[0])
print(fm1[0])

1.0
0.7078733207799225
18.2
12.8


Fit multiple Decision tree regressors on X_train data and Y_train labels with max_depth parameter value changing from 2 to 5.

Evaluate each model accuracy on testing data set.

Hint: Make use of for loop
Print the max_depth value of the model with highest accuracy.

In [75]:
dict ={}
for i in range(2,6):
    dt_reg=DecisionTreeRegressor(max_depth=i,random_state=30)
    dt_reg.fit(X_train,Y_train)
    dict[i]=dt_reg.score(X_test,Y_test)
Keymax = max(dict, key= lambda x: dict[x]) 
print(Keymax)

4


In [76]:
dict

{2: 0.6876109752166819,
 3: 0.7258833642668295,
 4: 0.7921505331200603,
 5: 0.765925079971153}

In [77]:
Keymax = max(dict, key= lambda x: dict[x]) 

In [78]:
Keymax

4