In [1]:
# Importing libraries
import numpy as np
import pandas as pd
%matplotlib inline 
import matplotlib.pyplot as plt
import seaborn as sns

from pandas.plotting import scatter_matrix

# for feature selection
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import VarianceThreshold

from sklearn import datasets


In [2]:
# Load iris data
iris = datasets.load_iris()

In [3]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
# Create features and target
X = iris.data
y = iris.target

In [11]:
# Create VarianceThreshold object with a variance with a threshold of 0.5
thresholder     = VarianceThreshold(threshold=.5)

thresholder.fit(X)

VarianceThreshold(threshold=0.5)

In [12]:
thresholder.get_params()

{'threshold': 0.5}

In [14]:
thresholder.get_support(indices=True)

array([0, 2, 3], dtype=int64)

In [11]:
# Variances of individual features.
thresholder.variances_

array([0.68112222, 0.18871289, 3.09550267, 0.57713289])

In [12]:
# Conduct variance thresholding
X_high_variance = thresholder.transform(X)

In [10]:
X_high_variance.shape

(150, 2)

In [13]:
# View first five rows with features with variances above threshold
X_high_variance[0: 5]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2]])