<a href="https://colab.research.google.com/github/Santanukolkata/Data_Science/blob/master/Models/Logistic_Regression/Logistic_Regression_on_Digits_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,fbeta_score,classification_report
import numpy as np
digits = load_digits()

In [20]:
X=digits.data

In [21]:
y=digits.target

In [29]:
##build model
X_train, X_test, y_train, y_test = train_test_split(X,
                                    y,train_size=0.8,random_state=71)

clf = LogisticRegression(random_state=125, solver='liblinear',C=.1,penalty='l1').fit(X_train,y_train)
predict_test = clf.predict(X_test)

In [28]:
print(confusion_matrix(y_test, predict_test))

[[31  0  0  0  0  1  0  0  0  0]
 [ 0 47  0  1  0  0  0  0  0  1]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 31  0  1  0  0  2  0]
 [ 0  1  0  0 44  0  0  0  0  0]
 [ 0  0  0  0  0 37  0  0  0  0]
 [ 0  0  0  0  0  1 29  0  0  0]
 [ 0  0  0  0  1  0  0 28  0  0]
 [ 0  3  0  0  1  0  0  0 29  0]
 [ 0  0  0  1  1  0  0  0  1 30]]


In [30]:
clf = LogisticRegression(random_state=125, solver='liblinear',C=.1,penalty='l2').fit(X_train,y_train)
predict_test = clf.predict(X_test)

In [31]:
print(confusion_matrix(y_test, predict_test))

[[31  0  0  0  0  1  0  0  0  0]
 [ 0 47  0  1  0  0  0  0  0  1]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 30  0  2  0  0  1  1]
 [ 0  1  0  0 44  0  0  0  0  0]
 [ 0  0  0  0  0 37  0  0  0  0]
 [ 0  0  0  0  0  1 29  0  0  0]
 [ 0  0  0  0  1  0  0 28  0  0]
 [ 0  3  0  0  1  0  0  0 29  0]
 [ 0  0  0  1  0  0  0  0  1 31]]
