In [1]:
import numpy as np

y = np.array([1, 2, 3, 4, 5])
x1 = np.array([6, 7, 8, 9, 10])
x2 = np.array([11, 12, 13, 14, 15])
X = np.vstack([np.ones(5), x1, x2, x1*x2])
# Transposing the records
X_Trans=np.vstack([np.ones(5), x1, x2, x1*x2]).T
print(X)
print(X_Trans)

[[  1.   1.   1.   1.   1.]
 [  6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.]
 [ 66.  84. 104. 126. 150.]]
[[  1.   6.  11.  66.]
 [  1.   7.  12.  84.]
 [  1.   8.  13. 104.]
 [  1.   9.  14. 126.]
 [  1.  10.  15. 150.]]


In [2]:
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np
boston_data=load_boston()
Boston=pd.DataFrame(boston_data.data,columns =list(boston_data.feature_names))

In [3]:
Boston.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

# Getting the some random 10 value

In [4]:
random_10=np.random.choice(Boston['ZN'],10)
print(random_10)
random_10.mean()

[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 95.]


9.5

In [10]:
import numpy as np
np.random.seed(10)

random_10=np.random.choice(Boston['ZN'],10)
print(random_10)
random_10.mean()

[20.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


2.0

In [17]:
geneated_array =np.random.normal(loc=Boston['ZN'].mean(), scale=Boston['ZN'].std(), size=100)

In [18]:
geneated_array.mean()

13.16087182545749

In [19]:
geneated_array

array([ 62.2142408 ,  15.80579124,  40.78924641,  21.10448461,
        32.21292253,  12.46807515,  -2.82633933,   5.10043514,
        -4.17616012,   3.34043665,  30.18606673,  61.31579176,
        -0.19539535,  23.62279048,   2.27612483,  33.22368986,
        -7.690206  ,  35.14356953,   3.40050371,  28.88536148,
         2.91503612, -14.97047416,   3.20753023, -13.18852842,
        41.26947384,   7.3567134 ,  24.8360393 , -23.03639594,
        13.2011764 ,  32.78329561,  -0.12727468,  13.6133755 ,
        -3.86032656,   6.19159233, -13.55142684, -17.26915386,
       -30.58349845,  -4.61707962, -21.51796404,  40.57264373,
        22.31499182,  18.98825112,  53.54330028, -21.59257559,
        70.2133006 ,  19.46393945,  -9.33176416, -13.34923703,
        19.47871795, -24.98824207, -11.8431612 ,  72.49534276,
         3.41332877,   7.58320301,  21.46131414,  11.25883789,
       -32.12624053,  -2.81002141,  72.44806034,  26.84025182,
        46.15172988,   6.98729505,  26.20843783,  49.08